enabled: true
vanillaRandomTickSpeed: 3
defaultTargetTickSpeed: 100
intervalTicks: 2
maxBlocksPerTickPerWorld: 2000
tripwire:
  maxLength: 69

worlds:
  world:
    enabled: true
    targetTickSpeed: 100
    maxBlocksPerTick: 2000

include:
  crops: true
  saplings: true
  bamboo: false
  sugarCane: false
  cactus: false
  hoppers: false

debug: false

autoUpdate:
  enabled: true
  checkOnStartup: true
  downloadOnUpdate: true
  repositoryOwner: starboyash
  repositoryName: Fast-Things
  channel: latest
